### PR TITLE
Cult dies if they visit when Wolf is at home

### PR DESCRIPTION
**Pull request by joshkurien**
Just seems to be a logical change event. Could happen on occasion of silverspread night for example

This change adds a new String for all language files though, have set up two as example

### CODE REVIEW

**Comment by renyhp** [comment]
Also, why is the new string in FurryNSFW.xml named CultConvertSerialKiller?

**Comment by parabola949** [comment]
`newbie.Property = <new value>`
Move all of these outside the loop.  Only the send should be looped.

Remove the string from FurryNSFW.xml - only English.xml changes should be done via github, all others are submitted to the bot on Telegram (so the bot can properly sync the language files to where they need to be, as well as validate the file)

**Comment by joshkurien** [comment]
Thanks for the advice @parabola949 and my bad @renyhp

**Comment by joshkurien** [comment]
Aah, I've made this a mess.. 3 commits; Please go ahead and squash merge the changes if you like

**Comment by renyhp** [comment]
Don't worry the number of commits is absolutely not a problem

**Pull request merged**
